name = "cloudflare-worker-cors"
main = 'worker.js'
usage_model = 'unbound'
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-11-15"

[vars]
ORIGIN_WHITELIST="https://mineskin.org,https://mcasset.cloud"
